package dev.openrp.weapons.bridge.food;

public enum FoodWorkstation {
    CUTTING_BOARD,
    STOVE,
    OVEN,
    PIZZA_OVEN,
    POT,
    PAN,
    GRILL,
    GRIDDLE,
    WATER_PURIFIER,
    SINK,
    TOASTER,
    FRIDGE,
    FREEZER,
    BAR_COUNTER,
    PASTRY_BENCH,
    ASSEMBLY_COUNTER,
    STREET_CART,
    FOOD_TRUCK,
    GELATO_COUNTER,
    ICE_CREAM_MACHINE,
    FRYER,
    BLENDER,
    MIXER,
    ICE_MACHINE,
    COFFEE_MACHINE,
    FERMENTER,
    MEAT_GRINDER,
    SLICER,
    PASTEURIZER,
    BOTTLER,
    KEG_TAP,
    DISTILLER
}
